version: '3.8'
services:
  fluentbit:
    build: .
    container_name: fluentbit
    hostname: docker-local
    ports:
      - "4318:4318"
    networks:
      - develop-bridge-network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M

networks:
  develop-bridge-network:
    name: develop-bridge
    external: true