version: '3.8'
services:
  otel-collector:
    image: dgandalcio/otel-collector:0.85.0
    container_name: otel-collector
    hostname: docker-local
    ports:
      - "4317"
      - "8888:8888"
    networks:
      - develop-bridge-network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M

networks:
  develop-bridge-network:
    name: develop-bridge
    external: true